Rebl/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from shop import views
from django.conf import settings
from django.conf.urls.static import static


# Routers provide an easy way of automatically determining the URL conf.


app_name = 'Rebl'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
    re_path('api/(?P<version>(v1|v2))/', include('shopapi.urls')),
    path('shop/', include('shop.urls')),
    path('imagefit/', include('imagefit.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views


# Routers provide an easy way of automatically determining the URL conf.

app_name = 'shop'
urlpatterns = [
    # Uri that conntects to api
    # search urlconfig MUST appear before 'productsbycategory'
    path('shoppingcart/', include('shoppingcart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('', views.entire_product_listing, name='index'),
    path('<slug:c_slug>/', views.entire_product_listing, name='productsbycategory'),
    path('<slug:c_slug>/<slug:product_slug>/', views.product_description, name='productdetail'),

]

shoppingcart/urls.py
from django.urls import path, include
from . import views


app_name = 'shoppingcart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.remove_from_cart,
         name='remove_from_cart'),
    path('full_remove/<int:product_id>/', views.full_remove,
         name='full_remove_from_cart')
]

shoppingcart/models.py
from django.db import models
from shop.models import Apparel_products

# Create your models here


class ShoppingCart(models.Model):
    """
     - implement shopping cart object with unique id per user
     - also, try to implement shopping cart object for a user with no account,
    closing/disconneccting with shop webpage will cause cart to empty.
    """
    # if blank is true, then user still has access to its cart?
    cart_id = models.CharField(max_length=250, blank=True)
    date_made = models.DateTimeField(auto_now_add=True)
    class Meta:
        """
        meta class in django is a container to store options, (ie, metadata),
        about the Model. From what I know, class Meta doesnt add any additional
        data to the Model, it just manipulates how the current data is
        accessed, permissions, etc, kinda of like quality of like changes
        """
        db_table = 'ShoppingCart'
        ordering = ['date_made']

    def __str__(self):
        """returns the carts unique id"""
        return self.cart_id

class ShoppingCartItem(models.Model):
    """
    items currently on sale at store that user put into cart
    - I think need to implement another class in shop app that encapsulates
    all products
    """
    # same product can be added to multiple users cart
    product = models.ForeignKey(on_delete=models.CASCADE, to=Apparel_products)
    shopping_cart = models.ForeignKey(ShoppingCart,
                                      on_delete=models.CASCADE)
    quantity = models.IntegerField()
    # for when item count in users cart <= 0  via the user removing items
    # or the server being updated while item user wants to purchase is still
    # in car
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'ShoppingCartItem'

    def amount_due(self):
        """calculates total pricing of items in users cart pre tax/shipping"""
        return (self.product.price*self.quantity)

    def __str__(self):
        return self.product

shoppingcart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Apparel_products
from .models import ShoppingCart, ShoppingCartItem
from order.models import Order, OrderItem
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMessage
import stripe
# Create your views here.


def _cart_id(request):
    """user/anon cart"""
    cart = request.session.session_key
    if cart is None:
        cart = request.session.create()
    return cart


def add_to_cart(request, product_id):
    # is this really needed?
    product = Apparel_products.objects.get(id=product_id)

    try:
        cart = ShoppingCart.objects.get(cart_id=_cart_id(request))
    except ShoppingCart.DoesNotExist:
        # create new shopping cart object
        cart = ShoppingCart.objects.create(cart_id=_cart_id(request))
        # saves and creates new session for user
        cart.save()
# add or not add product to cart if cart
    try:
        cart_item = ShoppingCartItem.objects.get(product=product,
                                                 shopping_cart=cart)
        # if there are less of a specific item in a persons cart than
        # overall stock, then it is valid to add to cart
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        # updates and saves current cart item count
        cart_item.save()
    except ShoppingCartItem.DoesNotExist:
        cart_item = ShoppingCartItem.objects.create(product=product,
                                                   shopping_cart=cart,
                                                   quantity=1
                                                   )
        cart_item.save()
    # pass in name of url config namespace to reverse call the view function
    return redirect('shop:shoppingcart:cart_detail')

def remove_from_cart(request, product_id):
    cart = ShoppingCart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Apparel_products, id=product_id)
    # queries for the item that is currently in sessions cart via product and shopping cart parameters

    cart_item = ShoppingCartItem.objects.get(product=product, shopping_cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('shop:shoppingcart:cart_detail')


def full_remove(request, product_id):
    """ fully removes an item from a unique cart"""
    cart = ShoppingCart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Apparel_products, id=product_id)
    cart_item = ShoppingCartItem.objects.get(product=product,
                                             shopping_cart=cart)
    cart_item.delete()
    return redirect('shop:shoppingcart:cart_detail')


def cart_detail(request, cart_items=None):
    """organizes cart stock according to database, all view calls from this
    file should have this function call as its final call
    - split into helper functions
    """
    count = 0
    total = 0
    try:
        cart = ShoppingCart.objects.get(cart_id=_cart_id(request))
        # add filter if doesnt work
        # only use objects.get() if you know for sure there is only 1
        # object matching your arguments, otherwise use filter
        cart_items = ShoppingCartItem.objects.filter(shopping_cart=cart,
                                                     active=True)

        for x in cart_items:
            print(x.quantity)
            total += x.product.price*x.quantity
            count += x.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)
    description = 'REBL SHOP - new order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    # seperate into helper here
    if request.method == 'POST':
        try:
            print(request.POST)
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            # billing info
            billing_name = request.POST['stripeBillingName']
            billing_address1 = request.POST['stripeBillingAddressLine1']
            billing_postalcode = request.POST['stripeBillingAddressZip']
            billing_country = request.POST['stripeBillingAddressCountryCode']
            billing_city = request.POST['stripeBillingAddressCity']
            # shipping info
            shipping_name = request.POST['stripeShippingName']
            shipping_address1 = request.POST['stripeShippingAddressLine1']
            shipping_postalcode = request.POST['stripeShippingAddressZip']
            shipping_country = request.POST['stripeShippingAddressCountryCode']
            shipping_city = request.POST['stripeShippingAddressCity']
            customer = stripe.Customer.create(source=token, email=email)
            charge = stripe.Charge.create(amount=stripe_total,
                                          currency='cad',
                                          customer=customer.id,
                                          description=description)
            # create and save order into database
            try:
                order_details = Order.objects.create(token=token,
                                                     total=total,
                                                     email=email,
                                                     billing_name=billing_name,
                                                     billing_address1=billing_address1,
                                                     billing_postalcode=billing_postalcode,
                                                     billing_country=billing_country,
                                                     billing_city=billing_city,
                                                     shipping_name=shipping_name,
                                                     shipping_address1=shipping_address1,
                                                     shipping_postalcode=shipping_postalcode,
                                                     shipping_country=shipping_country,
                                                     shipping_city=shipping_city)
                order_details.save()
                for ordered_item in cart_items:
                    oi=OrderItem.objects.create(product=ordered_item.product.name,
                                                quantity=ordered_item.quantity,
                                                price=ordered_item.product.price,
                                                order=order_details)
                    oi.save()
                    # reduce current shop stock based on succesful orders
                    product = Apparel_products.objects.get(id=ordered_item.product.id)
                    product.stock = ordered_item.product.stock - ordered_item.quantity
                    product.save()
                    # deletes all relations this order_item, thus item doesnt
                    # appear in cart views anymore
                    ordered_item.delete()
                    '''redirects to thank you page '''
                    try:
                        # call prebuilt function to send email to customer
                        customer_email(order_details.id)
                    except IOError as e:
                        # if email cannot be sent
                        return e
                    return redirect('shop:order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e

    context = {'cart_items': cart_items, 'count': count, 'total': total,
               'stripe_total': stripe_total, 'description': description,
               'data_key': data_key
               }

    return render(request, 'shoppingcart/cart.html', context)


# no request param needed
def customer_email(order_id):
    transaction = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order__id=order_id)
    try:
        # sending the order email to the customer
        subject = "REBL FOLLOW UP EMAIL - ORDER #: {}".format(order_id)
        to = ['{}'.format(transaction.email)]
        # sandbox email
        from_email = 'postmaster@sandboxe5d1dc112fc34991a23b5db05172fa28.mailgun.org'
        order_info = {'transaction': transaction, 'order_items': order_items}
        email_content = get_template('email/email.html').render(order_info)
        msg = EmailMessage(subject, email_content, to=to, from_email=from_email)
        msg.content_subtype = 'html'
        msg.send()
    except IOError as e:
        return e

shoppingcart/templates/shoppingcart/cart.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% block metadescription %}
    random shopping cart page  l o l
{% endblock %}
{% block title %}
    Shopping cart  - REBL
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">I am an empty cart!</h1>
            <br>
            <p class="text-center">please click <a href="{% url 'shop:index' %}">here</a>
                to be redirected to shop homepage!
            </p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center">
        <br>
        <h1 class="text-center my_title"> your shopping cart
        </h1>
        <br>
        </div>
    </div>
    <div class="mx-auto row">
        <div class="col-sm-12 col-md-12 col-lg-6 text-center col-12">
            <table class="custom_table table">
                <thead class="custom_thead">
                <tr>
                    <th colspan="5">
                        your items
                    </th>
                </tr>
                </thead>

                <tbody>
                {% for x in cart_items %}
                    <tr>
                    <!-- table cell -->
                        <td>
                            <!-- custom_image class resizes image -->
                            <a href="{{ x.product.get_absolute_url }}"><img src="{{ x.product.image.url }}" alt="a link"
                            class="float-left custom_image"></a>
                        </td>
                        <td class="text-left">
                        {{ x.product.name }}
                        <br>
                        SKU: {{ x.product.id }}
                        <br>
                        Unit Price: ${{ x.product.price }}
                        <br>
                        QTY: {{ x.quantity }} x {{ x.product.price }}
                        </td>
                        <td>
                            ${{ x.amount_due }}
                        </td>
                    {% if x.quantity < x.product.stock %}
                        <td>
                            <!-- second argument for url is int for product id -->
                            <!-- only implemented stock manipulation for adding stuff to cart, didnt do when deleting stuff from cart -->
                            <a href="{%  url 'shop:shoppingcart:add_cart' x.product.id %}" class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;
                        &nbsp;<a href="{% url 'shop:shoppingcart:remove_from_cart' x.product.id %}"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;
                            <a href="{% url 'shop:shoppingcart:full_remove_from_cart' x.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                        </td>
                    <!-- if we can't add more products to the cart -->
                    {% else %}
                     <td>
                        &nbsp;<a href="{% url 'shop:shoppingcart:remove_from_cart' x.product.id %}"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;
                         <a href="{% url 'shop:shoppingcart:remove_from_cart' x.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                     </td>
                    <td>

                    </td>
                    {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 text-center col-12">
            <table class="table custom_table">
                <thead class="custom_thead">
                    <tr>
                        <th>
                            <p>checkout!</p>
                        </th>
                    </tr>

                </thead>
            <tbody>
            <tr>
                <td>
                    review before ordering!
                </td>
            </tr>
            <tr>
                <td class="text-left">
                your total is <strong>${{ total }}</strong>
                </td>
            </tr>
            </tbody>
            </table>
        <div class="mx-auto">
            <!-- content after this doesnt display because of for....-->
            <form action="" method="POST">
                {% csrf_token %}
                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="{{ data_key }}"
                data-amount="{{ stripe_total }}"
                data-name="REBL"
                data-description='{{ description }}'
                data-image='{% static 'img/logo.jpg' %}'
                data-locale="auto"
                data-currency="cad"
                data-shipping-address="true"
                data-billing-address="true"
                data-zip-code="true">
                </script>
            </form>
            <a href="{% url 'shop:index' %}" class="btn btn-secondary btn-block custom_button"> click me to continue shopping</a>
        </div>
        </div>
    </div>
<br>
{% endif %}
{% endblock %}